site_name: Node Network Documentation
site_description: A collaborative AI network with recursive expert nodes
theme:
  name: material
nav:
  - Overview: index.md
  - Setup Guide: Setup.md
  - Roadmap: Roadmap.md
  - Contributing: Contributing.md
  - Portfolio:
      - Overview: portfolio/Portfolio.md
      - AI_Node: portfolio/AI_Node.md
      - Feedback Model: portfolio/Feedback_Model.md
      - Orchestrator: portfolio/Orchestrator.md
      - Final Deployment: portfolio/Final_Deployment.md
