jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Linting (Flake8)
        run: |
          source venv/bin/activate
          flake8 .

      - name: Run Tests (Pytest)
        env:
          PYTHONPATH: ${{ github.workspace }}  # Add project root to PYTHONPATH
        run: |
          source venv/bin/activate
          pytest
